GET http://127.0.0.1:5000/traveler/user_tickets
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMTQ2MTI4NywianRpIjoiMjYyZTc1NjctYjM0NS00NTBjLTg5NDMtNThmM2Y2MDlhOWI1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6OCwibmJmIjoxNzIxNDYxMjg3LCJjc3JmIjoiMDczNGU0ZDYtZDhjOC00NjVhLWFmNGEtOWNkNjRhODVmNGU3IiwiZXhwIjoxNzIxNDYyMTg3fQ.Mg-p1pgAORVvwHvHfpX2obGAG08r_6hJ9JPswYNXU4c
Content-Type: application/json



