GET http://127.0.0.1:5000/administrator/get_locations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMDY5NjA3NiwianRpIjoiM2JmZDY5YjQtNmMyMC00ZDZhLTkyMzMtMDhkNDllZTAwOWZkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MywibmJmIjoxNzIwNjk2MDc2LCJjc3JmIjoiZTBmZTE5NmUtMjc5My00MzIwLWJjYTEtM2YxZDgwNDg5ZWE1IiwiZXhwIjoxNzIwNjk2OTc2fQ.wgSfzp-I0YYzSlFWbJdSITCcXzAYnuSDc0045Ei0ZUM
Content-Type: application/json

